### ISSUE TITLE
Advanced Sampler audio out overload

### ISSUE THREAD

**Issue by Telerex** [LomasModules/LomasModules#8]
The audio out of the Advanced Sampler intermittently peaks high and sometimes negatively. I first noticed this when running it through the VCV delay  module, after which the delay would remain high and need deleting. Hopefully this is an easy fix for what is a neat little sampler.

**Comment by LomasModules** [comment]
What do you mean by peaks? The output is over +-5v? Or like really high voltage? Does happen with normal samples or recorded samples?

Ir should be easy to fix but more details will be helpful.

**Comment by Hawgk** [comment]
Having the same issue. Depending on the sample and pitch i use my audio output breaks needing a restart of VCV rack. According to the scope the peaks are different in amplitude. Highest i've been able to see were ca. +15V. I had a couple occurrances where the peak was out of the scopes range but no max value had been registered. I use SuperAnalogue 909 samples. Please let me know if you need any further details.

![Capture](https://user-images.githubusercontent.com/19670236/67242578-18167300-f456-11e9-98c3-5c904373c8ef.PNG)
![Capture_OOR](https://user-images.githubusercontent.com/19670236/67242577-18167300-f456-11e9-959c-530f196c3c15.PNG)

**Comment by Petervos2018** [comment]
See also #7 the DC part of the post.

**Comment by LomasModules** [comment]
I fixed this. It was a problem with uninitialized memory. I will push the update and a test version before uploading it to the module library.

**Comment by LomasModules** [comment]
This is fixed now. Allways initialize arrays to 0!

**Comment by Hawgk** [comment]
This isn't fixed for me. Still same issues as before: Heavy clicking and audio output breaking regularly. I used the 1.0.8. json file from here.
